package org.clevercastle.authforge.exception;

import org.clevercastle.authforge.CastleException;

public class UserNotFoundException extends CastleException {
    public UserNotFoundException() {
    }
}
